export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>PortfolioApp</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="monogram.svg">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
<style>body{background-color:#f1f3f5}
</style><link rel="stylesheet" href="styles-DEZSRBOS.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles-DEZSRBOS.css"></noscript><style ng-app-id="ng">.container[_ngcontent-ng-c3022078666]{margin-top:50px;text-align:left;width:90%;height:auto}.small-text-intro[_ngcontent-ng-c3022078666]{color:#333;font-weight:700;margin-bottom:5px}.big-name-text[_ngcontent-ng-c3022078666]{color:#333;font-size:72px;font-weight:700;margin-bottom:5px}.second-line[_ngcontent-ng-c3022078666]{color:#708238;font-size:62px;font-weight:700;margin-bottom:5}.paragraph[_ngcontent-ng-c3022078666]{width:550px}.paragraph-light[_ngcontent-ng-c3022078666]{font-weight:700;color:#333}.highlighted[_ngcontent-ng-c3022078666]{color:#708238}.image[_ngcontent-ng-c3022078666]{margin-top:50px}.image[_ngcontent-ng-c3022078666]   img[_ngcontent-ng-c3022078666]{height:300px;width:auto}.icons[_ngcontent-ng-c3022078666]{display:flex;flex-direction:column}.icons[_ngcontent-ng-c3022078666]   img[_ngcontent-ng-c3022078666]{height:50px;width:auto;margin-top:30px;margin-left:100px}.flex-box[_ngcontent-ng-c3022078666]{display:flex}</style></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["click"],[]);</script>
  <app-root ng-version="19.2.6" ngh="1" ng-server-context="ssg"><nav data-bs-theme="dark" class="navbar navbar-expand-lg bg-body-tertiary"><div class="container-fluid"><a href="#" class="navbar-brand"><img src="monogram.svg" alt="Logo" style="height: 50px;"></a><button type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span class="navbar-toggler-icon"></span></button><div id="navbarNavAltMarkup" class="collapse navbar-collapse"><div class="navbar-nav"><a routerlink="/" routerlinkactive="active" ariacurrentwhenactive="page" class="nav-link active" href="/" aria-current="page" jsaction="click:;">Home</a><a routerlink="/project" routerlinkactive="active" ariacurrentwhenactive="page" class="nav-link" href="/project" jsaction="click:;">Projects</a><a routerlink="/resume" routerlinkactive="active" ariacurrentwhenactive="page" class="nav-link" href="/resume" jsaction="click:;">Resume</a><a routerlink="/contact" routerlinkactive="active" ariacurrentwhenactive="page" class="nav-link" href="/contact" jsaction="click:;">Contact Me</a></div></div></div></nav><router-outlet></router-outlet><app-home _nghost-ng-c3022078666 ngh="0"><div _ngcontent-ng-c3022078666 class="container"><p _ngcontent-ng-c3022078666 class="small-text-intro">Hi, my name is</p><p _ngcontent-ng-c3022078666 class="big-name-text">Fahris Nassief.</p><p _ngcontent-ng-c3022078666 class="second-line">I build software to solve problems.</p><div _ngcontent-ng-c3022078666 class="paragraph"><p _ngcontent-ng-c3022078666 class="paragraph-light">I'm a computer science student at <span _ngcontent-ng-c3022078666 class="highlighted">Colorado State University</span>, working toward a career in software engineering. I have a strong interest in technology and enjoy solving real-world problems through code. This site highlights some of the projects I've worked on, along with what I'm learning along the way. Feel free to explore and don't hesitate to reach out. </p></div><div _ngcontent-ng-c3022078666 class="flex-box"><div _ngcontent-ng-c3022078666 class="image"><img _ngcontent-ng-c3022078666 src="version-control.svg" alt="man working on computer"></div><div _ngcontent-ng-c3022078666 class="icons"><a _ngcontent-ng-c3022078666 href="https://www.github.com/fahris-n" target="_blank"><img _ngcontent-ng-c3022078666 src="icons/github-brands.svg" alt="Github"></a><a _ngcontent-ng-c3022078666 href="https://www.linkedin.com/in/fahrisnassief" target="_blank"><img _ngcontent-ng-c3022078666 src="icons/linkedin-brands.svg" alt="LinkedIn"></a></div></div></div></app-home><!----></app-root>
<script src="polyfills-FFHMD2TL.js" type="module"></script><script src="main-RWLCF655.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{},{"c":{"16":[{"i":"c3022078666","r":1}]}}]}</script></body></html>`;